# Generated by Django 6.0.1 on 2026-02-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_review_product_rename_category_categorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='rating',
            field=models.ManyToManyField(blank=True, to='product.reviewmodel'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.categorymodel'),
        ),
    ]
