# Generated by Django 6.0.1 on 2026-02-03 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productmodel_rating_reviewmodel_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='rating',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categorymodel'),
        ),
    ]
